http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  registerApi:
    host: localhost
    paths: ["/registrationApi", "/registrationApi/*"]
  music:
    host: localhost
    paths: ["/musics", "/musics/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  registerService:
    url: "http://localhost:3000"
  musicService:
    url: "http://localhost:8000"
policies:
  - cors
  - expression
  - key-auth
  - jwt
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  registerApi:
    apiEndpoints:
      - registerApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: registerService
              changeOrigin: true
  musicPipeline:
    apiEndpoints:
      - music
    policies:
      - jwt:
          action:
            secretOrPublicKey: "../key.pem"
            checkCredentialExistence: false
